/*** LIST OF HTTP REQUEST MODULES ***/

//Request Modules
const request = require('request')
//Imports 'output.js'
const _ = require('./output')
//Imports 'request_options.js'
const request_options = require('./request_options')
//Deconstructs every module from 'request_options.js'
const {getHashLookUpOptions, getAnalyzeFileOptions, getFetchAnalysisResultsOptions} = request_options

/**
 * Produces output after performing hash lookup or fetching analysis results
 * @param filepath: path of a file
 * @param body: HTTP Response Body (JSON format)
 */
function produceOutput(filepath, body){
    // console.log(body)
    const {scan_results} = body
    if (scan_results) _.output(filepath, scan_results)
}


/**
 * Sends a request to perform a hash lookup based on a given file
 * @param api_key: API Key given by OPSWAT
 * @param hash_value: Hash value generated by a given text from a file
 * @param filepath: path of a file
 */
function sendHashLookUpHTTPRequest(api_key, hash_value, filepath){
    request(getHashLookUpOptions(api_key, hash_value), function (error, response, body) {
        
        if (error) throw new Error(error);
        // console.log(body)

        //Most likely, there is an invalid hash value and file needs to be uploaded
        if(body.error){       
            if(body.error.messages.includes('The hash was not found')){
                sendAnalyzeFileHTTPRequest(api_key, filepath)
            }
            return
        } 
            
        produceOutput(filepath, body)
    });
}

/**
 * Sends a request to analyze a file
 * @param api_key: API Key given by OPSWAT
 * @param filepath: path of a file
 */
function sendAnalyzeFileHTTPRequest(api_key, filepath){
    request(getAnalyzeFileOptions(api_key, filepath), function(error, response, body){
        if (error) throw new Error(error)

        console.log("After analyzing the file:")
        console.log(body)

        sendFetchAnalyisResultHTTPRequest(api_key, body.data_id, filepath)
    })
}

/**
 * Sends a request to fetch analysis results after uploading a file
 * @param api_key: API Key given by OPSWAT 
 * @param dataId: data Id retrieved after uploading a new file
 * @param filepath: path of a file
 */
function sendFetchAnalyisResultHTTPRequest(api_key, dataId, filepath){
    request(getFetchAnalysisResultsOptions(api_key, dataId), function(error, response, body){
        if (error) throw new Error(error)

        // console.log("After fetching analysis results:")
        // console.log(body)

        produceOutput(filepath, body)
    })
}

module.exports = {sendHashLookUpHTTPRequest}