/*** LIST OF HTTP OPTIONS FOR EACH REQUEST ***/



/**
 * Gets HTTP request options for hash lookup
 * @param api_key: API Key given by OPSWAT
 * @param hash_value: Hash value generated by a given text from a file
 * @returns 
 */
function getHashLookUpOptions(api_key, hash_value){
    return {
        "method": "GET",
        "url": `https://api.metadefender.com/v4/hash/${hash_value}`,
        "headers": {
        "apikey": api_key,
        },
        "body": "{}",
        "json": true
    }
}

/**
 * Gets HTTP request options for uploading a file
 * @param api_key: API Key given by OPSWAT
 * @param filename: name of a file
 * @returns 
 */
// function getAnalyzeFileOptions(api_key, filename){
//     return {
//         "method": "POST",
//         "url": "https://api.metadefender.com/v4/file",
//         "headers": {
//             "apikey": api_key,
//             "Content-Type": 'application/octet-stream',
//             "filename": filename.slice(2),
//         },
//         "body": "\"@/path/to/data.file\"",
//         "json": true
//     }
// }

/**
 * Gets HTTP request options for fetching analysis results
 * @param api_key: API Key given by OPSWAT
 * @param x_file_metadata
 * @param dataId: data Id retrieved after uploading a new file
 * @returns 
 */
// function getFetchAnalysisResultsOptions(api_key, x_file_metadata, dataId){
//     return {
//         "method": "GET",
//         "url": `https://api.metadefender.com/v4/file/${dataId}`,
//         "headers": {
//          "apikey": api_key,
//          "x-file-metadata": x_file_metadata
//         },
//         "body": "{}",
//         "json": true
//     }
// }

module.exports = {
    getHashLookUpOptions, 
    // getAnalyzeFileOptions, 
    // getFetchAnalysisResultsOptions
}